<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">';
echo '<meta name="description" content="">';
echo '<meta name="author" content="">';
echo '<link rel="preconnect" href="https://fonts.googleapis.com">';
echo '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>';
echo '<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">';
echo '';
echo '<title>DigiMedia - Creative SEO HTML5 Template</title>';
echo '';
echo '<!-- Bootstrap core CSS -->';
echo '<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">';
echo '';
echo '';
echo '<!-- Additional CSS Files -->';
echo '<link rel="stylesheet" href="assets/css/fontawesome.css">';
echo '<link rel="stylesheet" href="assets/css/templatemo-digimedia-v1.css">';
echo '<link rel="stylesheet" href="assets/css/animated.css">';
echo '<link rel="stylesheet" href="assets/css/owl.css">';
echo '<!--';
echo '';
echo 'https://templatemo.com/tm-568-digimedia';
echo '';
echo '-->';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<!-- ***** Preloader Start ***** -->';
echo '<div id="js-preloader" class="js-preloader">';
echo '<div class="preloader-inner">';
echo '<span class="dot"></span>';
echo '<div class="dots">';
echo '<span></span>';
echo '<span></span>';
echo '<span></span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- ***** Preloader End ***** -->';
echo '';
echo '<!-- Pre-header Starts -->';
echo '<!--<div class="pre-header">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-8 col-sm-8 col-7">';
echo '<ul class="info">';
echo '<li><a href="#"><i class="fa fa-envelope"></i>talent@Search.com</a></li>';
echo '<li><a href="#"><i class="fa fa-phone"></i>010-020-0340</a></li>';
echo '</ul>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-4 col-5">';
echo '<ul class="social-media">';
echo '<li><a href="#"><i class="fa fa-facebook"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-behance"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-twitter"></i></a></li>';
echo '<li><a href="#"><i class="fa fa-dribbble"></i></a></li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>-->';
echo '<!-- Pre-header End -->';
echo '';
echo '<!-- ***** Header Area Start ***** -->';
echo '<header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-12">';
echo '<nav class="main-nav">';
echo '<!-- ***** Logo Start ***** -->';
echo '<a href="homepage_1.php" class="logo">';
echo '<img src="assets/images/C1.jpg" alt=" LOGO">';
echo '</a>';
echo '<!-- ***** Logo End ***** -->';
echo '<!-- ***** Menu Start ***** -->';
echo '<ul class="nav">';
echo '<li class="scroll-to-section"><a href="#top" class="active">Home</a></li>';
echo '<li class="scroll-to-section"><a href="#about">About</a></li>';
echo '<li class="scroll-to-section"><a href="#services">Services</a></li>';
echo '<li class="scroll-to-section"><a href="search.php">Search Job</a></li>';
echo '<li class="scroll-to-section"><a href="#contact">Contact</a></li>';
echo '<li class="scroll-to-section"><a href="mainregister.php">Register</a></li>';
echo '<li class="scroll-to-section">';
echo '';
echo '<div class="main-menu">';
echo '<ul class="menu-list"><div class="border-first-button">';
echo '<li><a href="mainlogin.php"> Login </a>';
echo '<ul>';
//echo '<li><a href="#">Student Login </a></li>';
//echo '<li><a href="#">Company Login</a></li>';
//echo '<li><a href="#">Company Login</a></li>';
echo '</ul>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div></li>';
echo '</ul>';
//echo '<a class='menu-trigger'>';
//echo '<span>Menu</span>';
//echo '</a>';
echo '<!-- ***** Menu End ***** -->';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<!-- ***** Header Area End ***** -->';
echo '';
echo '<div class="main-banner wow fadeIn" id="top" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="row">';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="left-content show-up header-text wow fadeInLeft" data-wow-duration="1s" data-wow-delay="1s">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<h6>Digital Hiring</h6>';
echo '<h2>Towards Bright Future</h2>';
echo '<p>Acquiring the right TALENT is the most important key to growth . Hiring was - and still is - the most important thing we do .<br><br></p>';
echo '</div>';
echo '<div class="col-lg-12">';
echo '<div class="border-first-button scroll-to-section">';
echo '<a href="#contact">CONTACT US</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<div class="right-image wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<img src="assets/images/img1.png" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div id="about" class="about section">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="row">';
echo '<div class="col-lg-6">';
echo '<div class="about-left-image  wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<img src="assets/images/about-dec.png" alt="">';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 align-self-center  wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<div class="about-right-content">';
echo '<div class="section-heading">';
echo '<h2>About Us</h2>';
echo '<h4>Who are we ?</h4>';
echo '<div class="line-dec"></div>';
echo '</div>';
echo '<p>Campus Placement is an Placement cell Software which offers organizations with access to fresh talent. They can choose from a large pool of talent and hire in bulk for different roles and verticals. Campus Placement allows organizations to nurture new talent, from the beginning of their career journey, resulting in the development of better performing individuals and a lower attrition rate. Virtual campus recruitment ensures cost and time efficiency, accelerated and effective processes and decreased time-to-hire.<br></p>';
echo '<!--<div class="row">';
echo '<div class="col-lg-4 col-sm-4">';
echo '<div class="skill-item first-skill-item wow fadeIn" data-wow-duration="1s" data-wow-delay="0s">';
echo '<div class="progress" data-percentage="90">';
echo '<span class="progress-left">';
echo '<span class="progress-bar"></span>';
echo '</span>';
echo '<span class="progress-right">';
echo '<span class="progress-bar"></span>';
echo '</span>';
echo '<div class="progress-value">';
echo '<div>';
echo '90%<br>';
echo '<span>Coding</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-4">';
echo '<div class="skill-item second-skill-item wow fadeIn" data-wow-duration="1s" data-wow-delay="0s">';
echo '<div class="progress" data-percentage="80">';
echo '<span class="progress-left">';
echo '<span class="progress-bar"></span>';
echo '</span>';
echo '<span class="progress-right">';
echo '<span class="progress-bar"></span>';
echo '</span>';
echo '<div class="progress-value">';
echo '<div>';
echo '80%<br>';
echo '<span>Photoshop</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-4">';
echo '<div class="skill-item third-skill-item wow fadeIn" data-wow-duration="1s" data-wow-delay="0s">';
echo '<div class="progress" data-percentage="80">';
echo '<span class="progress-left">';
echo '<span class="progress-bar"></span>';
echo '</span>';
echo '<span class="progress-right">';
echo '<span class="progress-bar"></span>';
echo '</span>';
echo '<div class="progress-value">';
echo '<div>';
echo '80%<br>';
echo '<span>Animation</span>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div> -->';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div id="services" class="services section">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="section-heading  wow fadeInDown" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<h6>Our Services</h6>';
echo '<h4>What Our Placement Team<em>Provides</em></h4>';
echo '<div class="line-dec"></div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-12">';
echo '<div class="naccs">';
echo '<div class="grid">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="menu">';
echo '<div class="first-thumb active">';
echo '<div class="thumb">';
echo '<span class="icon"><img src="assets/images/service-icon-01.png" alt=""></span>';
echo '<br><br>Internship';
echo '</div>';
echo '</div>';
echo '<div>';
echo '<div class="thumb">';
echo '<span class="icon"><img src="assets/images/service-icon-02.png" alt=""></span>';
echo '<br><br>Placement';
echo '</div>';
echo '</div>';
echo '<div>';
echo '<div class="thumb">';
echo '<span class="icon"><img src="assets/images/service-icon-03.png" alt=""></span>';
echo 'Sessions by industry Experts';
echo '</div>';
echo '</div>';
echo '<div>';
echo '<div class="thumb">';
echo '<span class="icon"><img src="assets/images/service-icon-04.png" alt=""></span>';
echo 'Grooming Sessions by Placement cell';
echo '</div>';
echo '</div>';
echo '<!-- <div class="last-thumb">';
echo '<div class="thumb">';
echo '<span class="icon"><img src="assets/images/service-icon-01.png" alt=""></span>';
echo 'Traveling';
echo '</div>';
echo '</div>-->';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-12">';
echo '<ul class="nacc">';
echo '<li class="active">';
echo '<div>';
echo '<div class="thumb">';
echo '<div class="row">';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="left-text">';
echo '<h4>Intership  &amp; Reports</h4>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt ut labore et dolore kengan darwin doerski token.';
echo 'dover lipsum lorem and the others.</p>';
echo '<div class="ticks-list"><span><i class="fa fa-check"></i> Optimized Template</span> <span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span>';
echo '<span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span> <span><i class="fa fa-check"></i> Optimized Template</span></div>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="right-image">';
echo '<img src="assets/images/services-image.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div>';
echo '<div class="thumb">';
echo '<div class="row">';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="left-text">';
echo '<h4>Placement &amp; Details</h4>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt ut labore et dolore kengan darwin doerski token.';
echo 'dover lipsum lorem and the others.</p>';
echo '<div class="ticks-list"><span><i class="fa fa-check"></i> Optimized Template</span> <span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span>';
echo '<span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span> <span><i class="fa fa-check"></i> Optimized Template</span></div>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="right-image">';
echo '<img src="assets/images/services-image-02.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div>';
echo '<div class="thumb">';
echo '<div class="row">';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="left-text">';
echo '<h4>Car Re-search &amp; Transport</h4>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt ut labore et dolore kengan darwin doerski token.';
echo 'dover lipsum lorem and the others.</p>';
echo '<div class="ticks-list"><span><i class="fa fa-check"></i> Optimized Template</span> <span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span>';
echo '<span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span> <span><i class="fa fa-check"></i> Optimized Template</span></div>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="right-image">';
echo '<img src="assets/images/services-image-03.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div>';
echo '<div class="thumb">';
echo '<div class="row">';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="left-text">';
echo '<h4>Online Shopping &amp; Tracking ID</h4>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt ut labore et dolore kengan darwin doerski token.';
echo 'dover lipsum lorem and the others.</p>';
echo '<div class="ticks-list"><span><i class="fa fa-check"></i> Optimized Template</span> <span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span>';
echo '<span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span> <span><i class="fa fa-check"></i> Optimized Template</span></div>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="right-image">';
echo '<img src="assets/images/services-image-04.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '<li>';
echo '<div>';
echo '<div class="thumb">';
echo '<div class="row">';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="left-text">';
echo '<h4>Enjoy &amp; Travel</h4>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt ut labore et dolore kengan darwin doerski token.';
echo 'dover lipsum lorem and the others.</p>';
echo '<div class="ticks-list"><span><i class="fa fa-check"></i> Optimized Template</span> <span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span>';
echo '<span><i class="fa fa-check"></i> Data Info</span> <span><i class="fa fa-check"></i> SEO Analysis</span> <span><i class="fa fa-check"></i> Optimized Template</span></div>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sedr do eiusmod deis tempor incididunt.</p>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 align-self-center">';
echo '<div class="right-image">';
echo '<img src="assets/images/services-image.jpg" alt="">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</li>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '-->';
echo '';
echo '';
echo '<div id="free-quote" class="free-quote">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-4 offset-lg-4">';
echo '<div class="section-heading  wow fadeIn" data-wow-duration="1s" data-wow-delay="0.3s">';
echo '<h6>OUR MOTTO</h6>';
echo '<h4><em>Grow</em> With Us..</h4>';
echo '<div class="line-dec"></div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-8 offset-lg-2  wow fadeIn" data-wow-duration="1s" data-wow-delay="0.8s">';
echo '<form id="search" action="#" method="GET">';
echo '<div class="row">';
echo '<p style="font-size:1.6rem;color:rgb(24, 15, 15);"><br> To Prepare Students with Competencies and Employability Skills for their successful career.<br> Mission : To assist the student for their overall development.<br>To enrich and enhance the knowledge, competencies and attitudes of the students<br>To improve their soft skills.<br>To build life skills and self-confidence through value-based education.</p>';
echo '<div class="col-lg-4 col-sm-4">';
echo '<fieldset>';
echo '<input type="web" name="web" class="website"autocomplete="on" required>';
echo '</fieldset>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-4">';
echo '<fieldset>';
echo '<input type="address" name="address" class="email" autocomplete="on" required>';
echo '</fieldset>';
echo '</div>';
echo '<div class="col-lg-4 col-sm-4">';
echo '<fieldset>';
echo '<!--<button type="submit" class="main-button">Get Quote Now</button>-->';
echo '</fieldset>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '-->';
echo '';
echo '<div id="portfolio" class="our-portfolio section">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-5">';
echo '<div class="section-heading wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.3s">';
echo '<h6>Few of our</h6>';
echo '<h4>Reputed <em>Recruiters </em> Are</h4>';
echo '<div class="line-dec"></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container-fluid wow fadeIn" data-wow-duration="1s" data-wow-delay="0.7s">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="loop owl-carousel">';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/deloitte.jpg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>DELOITTE.</h4>';
echo '<!--  <span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/Amdocs.png" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>AMDOCS</h4>';
echo '<!--<span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/Zensar.jpg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>ZENSAR</h4>';
echo '<!--<span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/Tech Mahindra.png" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>TECH MAHINDRA</h4>';
echo '<!--<span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/KPMG.jpg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>KPMG</h4>';
echo '<!--<span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/Infosys.png" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>INFOSYS</h4>';
echo '<!--  <span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/Cognizant.jpg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>COGNIZANT</h4>';
echo '<!--  <span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/alfalaval.png" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>ALFA LAVAL</h4>';
echo '<!--  <span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/ibm.png" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>IBM</h4>';
echo '<!--  <span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/capgemini.jpg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>CAPGEMINI</h4>';
echo '<!--  <span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/wipro.jpg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>WIPRO</h4>';
echo '<!--  <span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="item">';
echo '<a href="#">';
echo '<div class="portfolio-item">';
echo '<div class="thumb">';
echo '<img src="assets/images/tcs.jpg" alt="">';
echo '</div>';
echo '<div class="down-content">';
echo '<h4>TATA CONSULATNCY SERVICES</h4>';
echo '<!--  <span>Marketing</span>-->';
echo '</div>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!--';
echo '<div id="blog" class="blog">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-4 offset-lg-4  wow fadeInDown" data-wow-duration="1s" data-wow-delay="0.3s">';
echo '<div class="section-heading">';
echo '<h6>Recent News</h6>';
echo '<h4>Check Our Blog <em>Posts</em></h4>';
echo '<div class="line-dec"></div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 show-up wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.3s">';
echo '<div class="blog-post">';
echo '<div class="thumb">';
echo '<a href="#"><img src="assets/images/blog-post-01.jpg" alt=""></a>';
echo '</div>';
echo '<div class="down-content">';
echo '<span class="category">SEO Analysis</span>';
echo '<span class="date">03 August 2021</span>';
echo '<a href="#"><h4>Lorem Ipsum Dolor Sit Amet, Consectetur Adelore';
echo 'Eiusmod Tempor Incididunt</h4></a>';
echo '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doers itii eiumod deis tempor incididunt ut labore.</p>';
echo '<span class="author"><img src="assets/images/author-post.jpg" alt="">By: Andrea Mentuzi</span>';
echo '<div class="border-first-button"><a href="#">Discover More</a></div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6 wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.3s">';
echo '<div class="blog-posts">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="post-item">';
echo '<div class="thumb">';
echo '<a href="#"><img src="assets/images/blog-post-02.jpg" alt=""></a>';
echo '</div>';
echo '<div class="right-content">';
echo '<span class="category">SEO Analysis</span>';
echo '<span class="date">24 September 2021</span>';
echo '<a href="#"><h4>Lorem Ipsum Dolor Sit Amei Eiusmod Tempor</h4></a>';
echo '<p>Lorem ipsum dolor sit amet, cocteturi adipiscing eliterski.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-12">';
echo '<div class="post-item">';
echo '<div class="thumb">';
echo '<a href="#"><img src="assets/images/blog-post-03.jpg" alt=""></a>';
echo '</div>';
echo '<div class="right-content">';
echo '<span class="category">SEO Analysis</span>';
echo '<span class="date">24 September 2021</span>';
echo '<a href="#"><h4>Lorem Ipsum Dolor Sit Amei Eiusmod Tempor</h4></a>';
echo '<p>Lorem ipsum dolor sit amet, cocteturi adipiscing eliterski.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-12">';
echo '<div class="post-item last-post-item">';
echo '<div class="thumb">';
echo '<a href="#"><img src="assets/images/blog-post-04.jpg" alt=""></a>';
echo '</div>';
echo '<div class="right-content">';
echo '<span class="category">SEO Analysis</span>';
echo '<span class="date">24 September 2021</span>';
echo '<a href="#"><h4>Lorem Ipsum Dolor Sit Amei Eiusmod Tempor</h4></a>';
echo '<p>Lorem ipsum dolor sit amet, cocteturi adipiscing eliterski.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '-->';
echo '<div id="contact" class="contact-us section">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-6 offset-lg-3">';
echo '<div class="section-heading wow fadeIn" data-wow-duration="1s" data-wow-delay="0.5s">';
echo '<h6>Contact Us</h6>';
echo '<h4>Get In Touch With Us <em>Now</em></h4>';
echo '<div class="line-dec"></div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-12 wow fadeInUp" data-wow-duration="0.5s" data-wow-delay="0.25s">';
echo '<form id="contact" action="" method="post">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<div class="contact-dec">';
echo '<img src="assets/images/contact-dec.png" alt="">';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-5">';
echo '<div id="map">';
echo '<iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+India&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="636px" frameborder="0" style="border:0" allowfullscreen></iframe>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-7">';
echo '<div class="fill-form">';
echo '<div class="row">';
echo '<div class="col-lg-4">';
echo '<div class="info-post">';
echo '<div class="icon">';
echo '<img src="assets/images/phone-icon.png" alt="">';
echo '<a href="#">010-020-0340</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="info-post">';
echo '<div class="icon">';
echo '<img src="assets/images/email-icon.png" alt="">';
echo '<a href="#">@gmail.com</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-4">';
echo '<div class="info-post">';
echo '<div class="icon">';
echo '<img src="assets/images/location-icon.png" alt="">';
echo '<a href="#">123 Rio de Janeiro</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<fieldset>';
echo '<input type="name" name="name" id="name" placeholder="Name" autocomplete="on" required>';
echo '</fieldset>';
echo '<fieldset>';
echo '<input type="text" name="email" id="email" pattern="[^ @]*@[^ @]*" placeholder="Your Email" required="">';
echo '</fieldset>';
echo '<fieldset>';
echo '<input type="subject" name="subject" id="subject" placeholder="Subject" autocomplete="on">';
echo '</fieldset>';
echo '</div>';
echo '<div class="col-lg-6">';
echo '<fieldset>';
echo '<textarea name="message" type="text" class="form-control" id="message" placeholder="Message" required=""></textarea>';
echo '</fieldset>';
echo '</div>';
echo '<div class="col-lg-12">';
echo '<fieldset>';
echo '<button type="submit" id="form-submit" class="main-button ">Send Message Now</button>';
echo '</fieldset>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<footer>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-lg-12">';
echo '<p>Copyright © 2022 Campus Placement . All Rights Reserved.';
echo '';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '';
echo '';
echo '<!-- Scripts -->';
echo '<script src="vendor/jquery/jquery.min.js"></script>';
echo '<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>';
echo '<script src="assets/js/owl-carousel.js"></script>';
echo '<script src="assets/js/animation.js"></script>';
echo '<script src="assets/js/imagesloaded.js"></script>';
echo '<script src="assets/js/custom.js"></script>';
echo '';
echo '</body>';
echo '</html>';
?>